spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:graphdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
      maximum-pool-size: 20

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

  graphql:
    graphiql:
      enabled: true
